Repository CUNY-CL/wikipron, pull requests merged in 2020-10, with the labels that each got.

#227 Added Serbo-Croatian phonemes and filtered TSV files.
  CHANGELOG.md
  data/README.md
  data/languages_summary.tsv
  data/phones/hbs_phonemic_phones.txt
  data/tsv/hbs_cyrl_phonemic_filtered.tsv
  data/tsv/hbs_latn_phonemic_filtered.tsv
Labels: language support

#226 Reorganizes tests and adds a few initial tests for the data side
  CHANGELOG.md
  data/__init__.py
  data/src/__init__.py
  data/src/generate_summary.py
  data/src/scrape.py
  tests/test_data/__init__.py
  tests/test_data/test_scrape.py
  tests/test_data/test_summary.py
  tests/test_wikipron/__init__.py
  tests/test_wikipron/test_cli.py
  tests/test_wikipron/test_config.py
  tests/test_wikipron/test_extract.py
  tests/test_wikipron/test_languagecodes.py
  tests/test_wikipron/test_scrape.py
  tests/test_wikipron/test_version.py
Labels: enhancement

#239 updated requirements.txt to have the latest dependencies (#238)
  CHANGELOG.md
  requirements.txt
Labels: hacktoberfest-accepted

#240 Added support for Python-3.9 (#236)
  .circleci/config.yml
  CHANGELOG.md
  setup.py
Labels: hacktoberfest-accepted

#242 Add black formatting
  .circleci/config.yml
  CHANGELOG.md
  data/src/codes.py
  data/src/scrape.py
  requirements.txt
  tests/test_data/test_scrape.py
  tests/test_wikipron/__init__.py
  tests/test_wikipron/test_config.py
  tests/test_wikipron/test_version.py
  wikipron/scrape.py
Labels: hacktoberfest-accepted

#247 ISSUE-241: Use mypy for type checking
  .circleci/config.yml
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  data/src/codes.py
  requirements.txt
  tests/test_data/__init__.py
  tests/test_data/test_scrape.py
  tests/test_wikipron/__init__.py
  tests/test_wikipron/test_extract.py
  wikipron/config.py
  wikipron/extract/cmn.py
  wikipron/extract/default.py
  wikipron/extract/jpn.py
  wikipron/extract/khb.py
  wikipron/extract/khm.py
  wikipron/extract/lat.py
  wikipron/extract/shn.py
  wikipron/extract/tha.py
  wikipron/extract/vie.py
  wikipron/scrape.py
Labels: hacktoberfest-accepted

#249 Improve CircleCI workflow
  .circleci/config.yml
  CHANGELOG.md
Labels: orbtoberfest
